config_1 = {
    "encoder": {
        "type": "transformer",
        "num_layers": 1,
        "num_heads": 4,
        "embeddings": {
            "embedding_dim": 256,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 256,
        "ff_size": 512,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
    "decoder": {
        "type": "transformer",
        "num_layers": 1,
        "num_heads": 4,
        "embeddings": {
            "embedding_dim": 256,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 256,
        "ff_size": 512,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
}
config_2 = {
    "encoder": {
        "type": "transformer",
        "num_layers": 1,
        "num_heads": 4,
        "embeddings": {
            "embedding_dim": 512,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 512,
        "ff_size": 1024,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
    "decoder": {
        "type": "transformer",
        "num_layers": 1,
        "num_heads": 4,
        "embeddings": {
            "embedding_dim": 512,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 512,
        "ff_size": 1024,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
}
config_3 = {
    "encoder": {
        "type": "transformer",
        "num_layers": 2,
        "num_heads": 4,
        "embeddings": {
            "embedding_dim": 256,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 256,
        "ff_size": 512,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
    "decoder": {
        "type": "transformer",
        "num_layers": 2,
        "num_heads": 4,
        "embeddings": {
            "embedding_dim": 256,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 256,
        "ff_size": 512,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
}
config_4 = {
    "encoder": {
        "type": "transformer",
        "num_layers": 2,
        "num_heads": 4,
        "embeddings": {
            "embedding_dim": 512,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 512,
        "ff_size": 1024,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
    "decoder": {
        "type": "transformer",
        "num_layers": 2,
        "num_heads": 4,
        "embeddings": {
            "embedding_dim": 512,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 512,
        "ff_size": 1024,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
}
config_5 = {
    "encoder": {
        "type": "transformer",
        "num_layers": 2,
        "num_heads": 8,
        "embeddings": {
            "embedding_dim": 256,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 256,
        "ff_size": 512,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
    "decoder": {
        "type": "transformer",
        "num_layers": 2,
        "num_heads": 8,
        "embeddings": {
            "embedding_dim": 256,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 256,
        "ff_size": 512,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
}
config_6 = {
    "encoder": {
        "type": "transformer",
        "num_layers": 2,
        "num_heads": 8,
        "embeddings": {
            "embedding_dim": 512,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 512,
        "ff_size": 1024,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
    "decoder": {
        "type": "transformer",
        "num_layers": 2,
        "num_heads": 8,
        "embeddings": {
            "embedding_dim": 512,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 512,
        "ff_size": 1024,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
}
config_7 = {
    "encoder": {
        "type": "transformer",
        "num_layers": 2,
        "num_heads": 16,
        "embeddings": {
            "embedding_dim": 256,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 256,
        "ff_size": 512,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
    "decoder": {
        "type": "transformer",
        "num_layers": 2,
        "num_heads": 16,
        "embeddings": {
            "embedding_dim": 256,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 256,
        "ff_size": 512,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
}
config_8 = {
    "encoder": {
        "type": "transformer",
        "num_layers": 2,
        "num_heads": 12,
        "embeddings": {
            "embedding_dim": 512,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 512,
        "ff_size": 1024,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
    "decoder": {
        "type": "transformer",
        "num_layers": 2,
        "num_heads": 12,
        "embeddings": {
            "embedding_dim": 512,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 512,
        "ff_size": 1024,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
}
config_9 = {
    "encoder": {
        "type": "transformer",
        "num_layers": 3,
        "num_heads": 4,
        "embeddings": {
            "embedding_dim": 256,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 256,
        "ff_size": 512,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
    "decoder": {
        "type": "transformer",
        "num_layers": 3,
        "num_heads": 4,
        "embeddings": {
            "embedding_dim": 256,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 256,
        "ff_size": 512,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
}
config_10 = {
    "encoder": {
        "type": "transformer",
        "num_layers": 3,
        "num_heads": 4,
        "embeddings": {
            "embedding_dim": 512,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 512,
        "ff_size": 1024,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
    "decoder": {
        "type": "transformer",
        "num_layers": 3,
        "num_heads": 4,
        "embeddings": {
            "embedding_dim": 512,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 512,
        "ff_size": 1024,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
}
config_11 = {
    "encoder": {
        "type": "transformer",
        "num_layers": 4,
        "num_heads": 4,
        "embeddings": {
            "embedding_dim": 256,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 256,
        "ff_size": 512,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
    "decoder": {
        "type": "transformer",
        "num_layers": 4,
        "num_heads": 4,
        "embeddings": {
            "embedding_dim": 256,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 256,
        "ff_size": 512,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
}
config_12 = {
    "encoder": {
        "type": "transformer",
        "num_layers": 4,
        "num_heads": 4,
        "embeddings": {
            "embedding_dim": 512,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 512,
        "ff_size": 1024,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
    "decoder": {
        "type": "transformer",
        "num_layers": 4,
        "num_heads": 4,
        "embeddings": {
            "embedding_dim": 512,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 512,
        "ff_size": 1024,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
}
config_13 = {
    "encoder": {
        "type": "transformer",
        "num_layers": 4,
        "num_heads": 8,
        "embeddings": {
            "embedding_dim": 256,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 256,
        "ff_size": 512,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
    "decoder": {
        "type": "transformer",
        "num_layers": 4,
        "num_heads": 8,
        "embeddings": {
            "embedding_dim": 256,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 256,
        "ff_size": 512,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
}
config_14 = {
    "encoder": {
        "type": "transformer",
        "num_layers": 4,
        "num_heads": 8,
        "embeddings": {
            "embedding_dim": 512,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 512,
        "ff_size": 1024,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
    "decoder": {
        "type": "transformer",
        "num_layers": 4,
        "num_heads": 8,
        "embeddings": {
            "embedding_dim": 512,
            "scale": True,
            "freeze": False,
            "dropout": 0.0,
        },
        "hidden_size": 512,
        "ff_size": 1024,
        "dropout": 0.2,
        "freeze": False,
        "layer_norm": "pre",
        "activation": "relu",
    },
}


transformer_modes = {
    1: config_1,
    2: config_2,
    3: config_3,
    4: config_4,
    5: config_5,
    6: config_6,
    7: config_7,
    8: config_8,
    9: config_9,
    10: config_10,
    11: config_11,
    12: config_12,
    13: config_13,
    14: config_14,
}
